name: Ola, Mundo!

on: [push]

jobs: 
  ola_mundo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Ola, Mundo!
        run: echo "Ola, Mundo!"